const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const repoRoot = path.join(__dirname, "..", "..");
const read = (...parts) => fs.readFileSync(path.join(repoRoot, ...parts), "utf8");

test("beta feedback loop wires authenticated submission to the protected admin review surface", () => {
  const widget = read("apps", "web", "components", "feedback-widget.tsx");
  const client = read("apps", "web", "lib", "textplex.ts");
  const adminPage = read("apps", "web", "app", "admin", "feedback", "page.tsx");
  const adminView = read("apps", "web", "components", "admin-feedback-view.tsx");
  const notificationBell = read("apps", "web", "components", "feedback-notification-bell.tsx");
  const appShell = read("apps", "web", "components", "app-shell.tsx");
  const accountFooter = read("apps", "web", "components", "account-footer.tsx");
  const testerConsole = read("apps", "web", "components", "tester-console-view.tsx");
  const testerPage = read("apps", "web", "app", "tester", "page.tsx");
  const buildFooter = read("apps", "web", "components", "build-footer.tsx");
  const reader = read("apps", "web", "components", "reader-view.tsx");
  const feedbackEvents = read("apps", "web", "lib", "feedback-events.ts");
  const stylesheet = read("apps", "web", "app", "globals.css");
  const inventory = read("docs", "COMPONENTS_INVENTORY.md");

  assert.match(widget, /submitFeedback\(trimmedMessage, submissionContext\)/);
  assert.match(widget, /submitFeedbackWithScreenshots\(trimmedMessage, submissionContext, screenshots\)/);
  assert.match(widget, /READER_FEEDBACK_REQUEST_EVENT/);
  assert.match(widget, /feedback_target_text/);
  assert.match(widget, /type="file"/);
  assert.match(widget, /multiple/);
  assert.match(widget, /accept="image\/png,image\/jpeg,image\/webp,image\/gif"/);
  assert.match(widget, /aria-label="Close feedback dialog"/);
  assert.match(widget, /data-inventory-id="shell\.feedback-close-button"/);
  assert.match(stylesheet, /\.app-feedback-close-button\s*\{[\s\S]*?flex: 0 0 3rem;[\s\S]*?min-width: 3rem;[\s\S]*?min-height: 3rem;/);
  assert.match(stylesheet, /\.app-feedback-close-button svg\s*\{[\s\S]*?width: 1\.25rem;[\s\S]*?height: 1\.25rem;/);
  assert.match(client, /postJson<FeedbackRecord>\("\/feedback", \{ original_text: originalText, context \}\)/);
  assert.match(client, /postFormData<FeedbackRecord>\("\/feedback\/with-screenshot", body\)/);
  assert.match(client, /screenshot-analysis/);
  assert.match(client, /fetchWithAuth\(pathname,/);
  assert.match(adminPage, /<AdminOnly>/);
  assert.match(adminPage, /<AdminFeedbackView \/>/);
  assert.match(adminView, /fetchJson<\{ records: FeedbackRecord\[\] \}>\("\/feedback"\)/);
  assert.match(adminView, /patchJson<FeedbackRecord>\(`\/feedback\/\$\{selectedRecord\.id\}\/status`/);
  assert.match(adminView, /Unknown tester/);
  assert.match(adminView, /PencilIcon/);
  assert.match(adminView, /admin-feedback-icon-button/);
  assert.match(adminView, /expandedTesterId/);
  assert.match(adminView, /admin-feedback\.summary/);
  assert.match(adminView, /admin-feedback\.metrics/);
  assert.match(adminView, /testerFilter/);
  assert.match(adminView, /screenshotFilter/);
  assert.match(adminView, /feedbackMetrics/);
  assert.match(adminView, /Average time to resolution/);
  assert.match(adminView, /feedbackSummary/);
  assert.match(adminView, /admin-feedback\.resolution/);
  assert.match(adminView, /Resolution note/);
  assert.match(adminView, /ready_for_testing/);
  assert.match(adminView, /implementationBuildDraft/);
  assert.match(adminView, /verificationInstructionsDraft/);
  assert.doesNotMatch(adminView, /window\.prompt\(`Optional note/);
  assert.match(notificationBell, /submitFeedbackVerification/);
  assert.match(notificationBell, /Works for me/);
  assert.match(notificationBell, /Still happening/);
  assert.match(appShell, /FeedbackNotificationBell placement="top"/);
  assert.doesNotMatch(accountFooter, /FeedbackNotificationBell/);
  assert.match(testerPage, /TesterConsoleView/);
  assert.match(testerConsole, /\/feedback\/mine/);
  assert.match(testerConsole, /tester\.timeline/);
  assert.match(testerConsole, /tester\.verification/);
  assert.match(testerConsole, /Works for me/);
  assert.match(buildFooter, /Build <strong>\{version\}<\/strong>/);
  assert.match(adminView, /Analyze screenshots with AI/);
  assert.match(adminView, /admin-feedback\.screenshots/);
  assert.match(reader, /reader\.sentence-feedback-button/);
  assert.match(reader, /reader\.definition-correction-button/);
  assert.match(feedbackEvents, /textplex:reader-feedback-request/);
  assert.match(inventory, /`admin-feedback\.page`[^\n]*Admin-only feedback review surface/);
  assert.match(inventory, /`reader\.sentence-feedback-button`/);
  assert.match(inventory, /`reader\.definition-correction-button`/);
  assert.match(inventory, /`shell\.feedback-close-button`[^\n]*Close feedback dialog/);
  assert.match(inventory, /`shell\.feedback-close-button`[^\n]*\[#124\]/);
});
