import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const read = (...parts) => readFileSync(resolve(root, ...parts), "utf8");

test("TXT upload support is wired through the live and demo import surfaces", () => {
  const liveImport = read("apps", "web", "components", "surface-views.tsx");
  const demoImport = read("apps", "web", "components", "mock-route-views.tsx");
  const demoData = read("apps", "web", "lib", "demo-data.ts");
  const sharedContract = read("packages", "shared", "src", "contracts.ts");
  const apiClient = read("apps", "web", "lib", "textplex.ts");
  const compose = read("docker-compose.yml");
  const appendCard = read("apps", "web", "components", "photo-page-append-card.tsx");
  const bookDetail = read("apps", "web", "components", "book-detail-view.tsx");
  const reader = read("apps", "web", "components", "reader-view.tsx");

  assert.match(liveImport, /\.endsWith\("\.txt"\)/);
  assert.match(liveImport, /text\/plain,\.txt/);
  assert.match(liveImport, /PDF, EPUB, or TXT/);
  assert.match(demoImport, /supported_inputs: \["pdf", "epub", "txt"/);
  assert.match(demoData, /supported_inputs: \["pdf", "epub", "txt"/);
  assert.match(sharedContract, /can_upload_txt: boolean/);
  assert.match(liveImport, /Add photos page by page/);
  assert.match(liveImport, /\/books\/upload-images/);
  assert.match(liveImport, /append\("images", page\.file, page\.file\.name\)/);
  assert.match(liveImport, /function createPhotoPageId\(file: File\)/);
  assert.match(liveImport, /globalThis\.crypto\?\.randomUUID\?\.\(\) \?\?/);
  assert.match(sharedContract, /can_upload_images: boolean/);
  assert.match(apiClient, /function effectiveApiBaseUrl\(\)/);
  assert.match(apiClient, /configuredHost === "localhost"/);
  assert.match(apiClient, /return "\/api"/);
  assert.match(compose, /TEXTPLEX_BROWSER_API_URL:-\/api/);
  assert.match(compose, /TEXTPLEX_WEB_API_ORIGIN:-http:\/\/api:8000/);
  assert.match(sharedContract, /source_type\?: "static" \| "page-by-page"/);
  assert.match(appendCard, /\/append-images/);
  assert.match(appendCard, /surface\.page-by-page-append-card/);
  assert.match(appendCard, /capture="environment"/);
  assert.match(appendCard, /multiple onChange/);
  assert.match(bookDetail, /book\.source_type === "page-by-page"/);
  assert.match(reader, /isPageByPageSource/);
  assert.match(appendCard, /reader\.page-frontier-upload-button/);
  assert.match(reader, /reader\.page-upload-input-mode/);
  assert.match(reader, /reader\.end-of-content-page/);
  assert.match(reader, /Session paused/);
  assert.match(appendCard, /OCR\/transcription/);
  assert.match(reader, /Go to previous page/);
  assert.match(reader, /Exit reader/);
  assert.match(reader, /force: false/);
});
