const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const repoRoot = path.join(__dirname, "..", "..");
const surfaceSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "surface-views.tsx"), "utf8");
const mockSurfaceSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "mock-route-views.tsx"), "utf8");
const layoutSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "app", "layout.tsx"), "utf8");
const themeSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "lib", "theme.ts"), "utf8");
const themeCatalogSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "lib", "theme-catalog.ts"), "utf8");
const themeToggleSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "theme-toggle-button.tsx"), "utf8");
const appShellSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "app-shell.tsx"), "utf8");
const stylesheetSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "app", "globals.css"), "utf8");

test("Settings menu cards use the shared route card spacing", () => {
  assert.match(surfaceSource, /settings-preferences-card[\s\S]*settings-developer-tools-card/);
  assert.match(mockSurfaceSource, /settings-preferences-card[\s\S]*settings-roadmap-card/);
  assert.match(surfaceSource, /settings\.theme-settings-link/);
  assert.match(mockSurfaceSource, /settings\.theme-settings-link/);
  assert.match(surfaceSource, /settings\.inventory-labels-toggle/);
  assert.match(mockSurfaceSource, /settings\.inventory-labels-toggle/);
  assert.match(surfaceSource, /settings\.speech-voice-toggle/);
  assert.match(mockSurfaceSource, /settings\.speech-voice-toggle/);
  assert.match(surfaceSource, /readerSpeechVoiceGender/);
  assert.match(mockSurfaceSource, /readerSpeechVoiceGender/);
  assert.match(surfaceSource, /voice-gender-toggle-group/);
  assert.match(mockSurfaceSource, /voice-gender-toggle-group/);
  assert.match(surfaceSource, /Female/);
  assert.match(surfaceSource, /Male/);
  assert.match(mockSurfaceSource, /Female/);
  assert.match(mockSurfaceSource, /Male/);
  assert.match(surfaceSource, /InventoryInspectorToggle/);
  assert.match(mockSurfaceSource, /InventoryInspectorToggle/);
  assert.match(surfaceSource, /isTextPlexAdmin/);
  assert.match(surfaceSource, /settings\.developer-tools-card/);
  assert.match(themeToggleSource, /shell\.theme-toggle/);
  assert.match(layoutSource, /<ThemeProvider>/);
  assert.match(layoutSource, /generateViewport/);
  assert.match(layoutSource, /APP_THEME_COOKIE_KEY/);
  assert.match(layoutSource, /prefers-color-scheme: light/);
  assert.match(layoutSource, /prefers-color-scheme: dark/);
  assert.match(layoutSource, /localStorage\.getItem\("textplex\.themeFollowSystem"\) === "on"/);
  assert.match(layoutSource, /document\.cookie = "textplex\.theme="/);
  assert.match(layoutSource, /meta\[name="color-scheme"\]/);
  assert.match(themeSource, /querySelectorAll<HTMLMetaElement>\('meta\[name="theme-color"\]'\)/);
  assert.match(appShellSource, /shell\.back-button/);
  assert.match(appShellSource, /shell\.theme-settings/);
  assert.match(appShellSource, /theme-toggle-button shell-icon-button app-shell-back-button/);
  assert.match(appShellSource, /theme-toggle-button shell-icon-button app-shell-theme-settings/);
  assert.match(appShellSource, /href="\/profile\/themes"/);
  assert.match(appShellSource, /Open theme settings/);
  assert.match(appShellSource, /Go back/);
  assert.match(appShellSource, /className="button button-secondary nav-link nav-link-home" href=\{HOME_PATH\}/);
  assert.match(appShellSource, /className="button button-secondary nav-link nav-link-home"/);
  assert.match(stylesheetSource, /\.app-shell\s*\{[\s\S]*display: grid;[\s\S]*gap: 1rem;/);
  assert.match(stylesheetSource, /\.shell-icon-button,\s*\.button\.theme-toggle-button\s*\{[\s\S]*width: 2\.4rem;/);
  assert.match(stylesheetSource, /\.app-shell-back-button\s*\{[\s\S]*left: 0\.35rem;/);
  assert.match(surfaceSource, /ThemeSettingsSurfaceView/);
  assert.match(surfaceSource, /theme-settings\.app-theme-card/);
  assert.match(surfaceSource, /theme-settings\.behavior-card/);
  assert.match(surfaceSource, /id="theme-catalog"/);
});

test("Strawberry daylight and night variants share catalog and wallpaper wiring", () => {
  assert.match(themeSource, /fruit-strawberry-night/);
  assert.match(themeSource, /"fruit-strawberry": "fruit-strawberry-night"/);
  assert.match(themeSource, /"fruit-strawberry-night": "fruit-strawberry"/);
  assert.match(themeCatalogSource, /"fruit-strawberry": \[/);
  assert.match(themeCatalogSource, /\{ version: 6, path: "\/themes\/fruit-strawberry-v6\.png" \}/);
  assert.match(themeCatalogSource, /"fruit-strawberry-night": \[\{ version: 1, path: "\/themes\/fruit-strawberry-night-v1\.png" \}\]/);
  assert.match(themeCatalogSource, /themeWallpaperAssetCandidates/);
  assert.match(themeCatalogSource, /candidate\.version > latest\.version/);
  assert.match(stylesheetSource, /html\[data-app-theme="fruit-strawberry-night"\]/);
  assert.match(stylesheetSource, /\.global-theme-swatch\[data-theme="fruit-strawberry-night"\]/);
  assert.match(stylesheetSource, /\.reader-theme-option-swatch\[data-theme="fruit-strawberry-night"\]/);
  assert.match(layoutSource, /"fruit-strawberry-night": "#1a0d1b"/);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "fruit-strawberry-v1.jpg")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "fruit-strawberry-v6.png")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "fruit-strawberry-night-v1.png")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "fruit-strawberry.jpg")), false);
});

test("Hong Kong daylight and night variants use the latest paired wallpaper assets", () => {
  assert.match(themeSource, /city-hong-kong-daylight/);
  assert.match(themeSource, /"city-hong-kong-daylight": "city-hong-kong-night"/);
  assert.match(themeSource, /"city-hong-kong-night": "city-hong-kong-daylight"/);
  assert.match(themeCatalogSource, /"city-hong-kong-daylight": \[/);
  assert.match(themeCatalogSource, /\{ version: 3, path: "\/themes\/city-hong-kong-daylight-v3\.jpg" \}/);
  assert.match(themeCatalogSource, /"city-hong-kong-night": \[\{ version: 1, path: "\/themes\/city-hong-kong-night-v1\.png" \}\]/);
  assert.match(stylesheetSource, /html\[data-app-theme="city-hong-kong-daylight"\]/);
  assert.match(stylesheetSource, /html\[data-app-theme="city-hong-kong-night"\]/);
  assert.match(stylesheetSource, /\.global-theme-swatch\[data-theme="city-hong-kong-daylight"\]/);
  assert.match(stylesheetSource, /\.reader-theme-option-swatch\[data-theme="city-hong-kong-night"\]/);
  assert.match(layoutSource, /"city-hong-kong-night": "#0b1b2a"/);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "city-hong-kong-daylight-v1.png")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "city-hong-kong-daylight-v2.png")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "city-hong-kong-daylight-v3.jpg")), true);
  assert.equal(fs.existsSync(path.join(repoRoot, "apps", "web", "public", "themes", "city-hong-kong-night-v1.png")), true);
});
