const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const repoRoot = path.join(__dirname, "..", "..");
const studySource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "surface-views.tsx"), "utf8");
const mockStudySource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "mock-route-views.tsx"), "utf8");
const stylesheetSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "app", "globals.css"), "utf8");

test("Study route expands saved vocabulary rows to show full metadata", () => {
  assert.match(studySource, /study\.programs-card/);
  assert.match(studySource, /study\.program-group/);
  assert.match(studySource, /study\.program-level/);
  assert.match(studySource, /study\.program-item/);
  assert.match(studySource, /Program introduction/);
  assert.match(studySource, /Practice this level/);
  assert.match(studySource, /study\.program-practice-link-summary/);
  assert.match(studySource, /study\.queue-card/);
  assert.match(studySource, /study-queue-card-summary/);
  assert.match(studySource, /study-queue-actions/);
  assert.match(studySource, /DueReviewChart/);
  assert.match(studySource, /Due items/);
  assert.match(studySource, /Tap a language card for review pills and timing\./);
  assert.match(studySource, /Start review session/);
  assert.match(studySource, /study\.review-practice-link/);
  assert.match(studySource, /study\.queue-language-group/);
  assert.match(studySource, /study\.queue-language-group-toggle/);
  assert.match(studySource, /study\.queue-language-group-details/);
  assert.match(studySource, /study\.queue-language-term-pill/);
  assert.match(studySource, /study\.queue-language-start-now/);
  assert.match(studySource, /language_code=/);
  assert.match(studySource, /study\.queue-language-notify/);
  assert.match(mockStudySource, /study\.programs-card/);
  assert.match(mockStudySource, /study\.program-group/);
  assert.match(mockStudySource, /study\.program-level/);
  assert.match(mockStudySource, /study\.program-item/);
  assert.match(mockStudySource, /Program introduction/);
  assert.match(mockStudySource, /Practice this level/);
  assert.match(mockStudySource, /study\.queue-card/);
  assert.match(mockStudySource, /study-queue-card-summary/);
  assert.match(mockStudySource, /study-queue-actions/);
  assert.match(mockStudySource, /DueReviewChart/);
  assert.match(mockStudySource, /Due items/);
  assert.match(mockStudySource, /Tap a language card for review pills and timing\./);
  assert.match(mockStudySource, /study\.queue-language-group/);
  assert.match(mockStudySource, /study\.queue-language-group-toggle/);
  assert.match(mockStudySource, /study\.queue-language-group-details/);
  assert.match(mockStudySource, /study\.queue-language-term-pill/);
  assert.match(mockStudySource, /study\.queue-language-start-now/);
  assert.match(mockStudySource, /language_code=/);
  assert.match(mockStudySource, /study\.queue-language-notify/);
  assert.match(studySource, /study\.saved-vocabulary-card/);
  assert.match(studySource, /study-language-group-summary/);
  assert.match(studySource, /<details key=\{group\.language_code\} className="study-language-group" data-inventory-id="study\.language-group">/);
  assert.doesNotMatch(studySource, /study-language-group" data-inventory-id="study\.language-group" open/);
  assert.match(studySource, /study\.saved-item-toggle/);
  assert.match(studySource, /study-saved-item-row/);
  assert.match(studySource, /study-saved-item-term/);
  assert.match(studySource, /study-saved-item-pronunciation/);
  assert.match(studySource, /study-saved-item-meaning/);
  assert.match(studySource, /English meaning/);
  assert.match(studySource, /\(\{pronunciation\}\)/);
  assert.match(studySource, /study\.saved-item-details/);
  assert.match(studySource, /study-metadata-grid/);
  assert.match(studySource, /Current note/);
  assert.match(studySource, /Source sentence/);
  assert.match(mockStudySource, /study-language-group-summary/);
  assert.match(mockStudySource, /<details key=\{group\.language_code\} className="study-language-group" data-inventory-id="study\.language-group">/);
  assert.doesNotMatch(mockStudySource, /study-language-group" data-inventory-id="study\.language-group" open/);
  assert.match(mockStudySource, /study\.saved-item-toggle/);
  assert.match(mockStudySource, /study-saved-item-row/);
  assert.match(mockStudySource, /English meaning/);
  assert.match(mockStudySource, /\(\{pronunciation\}\)/);
  assert.match(mockStudySource, /study\.saved-item-details/);
  assert.match(mockStudySource, /Demo metadata dump for the study surface/);
  assert.match(stylesheetSource, /study-language-group\[open\] \.study-language-group-summary::after[\s\S]*content: "-";/);
  assert.match(stylesheetSource, /study-program-group\[open\] \.study-program-group-summary::after[\s\S]*content: "-";/);
});
