const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const repoRoot = path.join(__dirname, "..", "..");
const practiceSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "study-practice-view.tsx"), "utf8");
const pronunciationGuideSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "study-pronunciation-guide.tsx"), "utf8");
const practicePageSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "app", "study", "practice", "page.tsx"), "utf8");

test("Study practice route exposes a one-card drill flow", () => {
  assert.match(practicePageSource, /export const dynamic = "force-dynamic";/);
  assert.match(practicePageSource, /<Suspense fallback={<section className="card feature-card">Loading practice session\.\.\.<\/section>}>/);
  assert.match(practicePageSource, /StudyPracticeView/);
  assert.match(practicePageSource, /modeValue === "review" \|\| modeValue === "glossed" \|\| modeValue === "both"/);
  assert.match(practicePageSource, /initialMode={mode}/);
  assert.match(practicePageSource, /initialProgramCode={programCode}/);
  assert.match(practicePageSource, /initialLevelCode={levelCode}/);
  assert.match(practicePageSource, /initialAssessmentAxisKey={assessmentAxisKey}/);
  assert.match(practicePageSource, /firstSearchParam\(searchParams\.program_code\) \?\? firstSearchParam\(searchParams\.program\)/);
  assert.match(practicePageSource, /firstSearchParam\(searchParams\.level_code\) \?\? firstSearchParam\(searchParams\.level\)/);

  assert.match(practiceSource, /Vocabulary practice session/);
  assert.match(practiceSource, /useSearchParams/);
  assert.match(practiceSource, /buildProgramCards/);
  assert.match(practiceSource, /buildGlossedCards/);
  assert.match(practiceSource, /selectPracticeProgramLevel/);
  assert.match(practiceSource, /data\.study_programs\.find\(\(program\) => program\.program_code === programCode\)/);
  assert.match(practiceSource, /buildReviewCards/);
  assert.match(practiceSource, /INTRODUCTION_CHUNK_SIZE = 5/);
  assert.match(practiceSource, /INTRODUCTION_AXIS_ORDER/);
  assert.match(practiceSource, /practiceModeLabel/);
  assert.match(practiceSource, /phase: "intro"/);
  assert.match(practiceSource, /phase: "assessment"/);
  for (const axisKey of ["form_to_meaning", "form_to_reading", "meaning_to_form", "reading_to_form"]) {
    assert.match(practiceSource, new RegExp(axisKey));
  }
  assert.match(practiceSource, /Next practice chunk/);
  assert.match(practiceSource, /Start practice/);
  assert.match(practiceSource, /Next word/);
  assert.match(practiceSource, /Learn this word before we move into the randomized axis checks for this chunk\./);
  assert.match(practiceSource, /Type the romanization/);
  assert.match(practiceSource, /Type the \$\{card\.languageLabel\} term/);
  assert.match(practiceSource, /Type the English meaning/);
  assert.match(practiceSource, /RETRY_SIMILARITY_THRESHOLD = 0\.75/);
  assert.match(practiceSource, /levenshteinDistance/);
  assert.match(practiceSource, /answerSimilarityRatio/);
  assert.match(practiceSource, /study\.practice-card/);
  assert.match(practiceSource, /StudyPronunciationGuide/);
  assert.match(practiceSource, /showPronunciationGuide/);
  assert.match(practiceSource, /currentCard\.phase === "intro" && resolvedPronunciation/);
  assert.match(practiceSource, /currentCard\.phase === "intro"/);
  assert.match(practiceSource, /currentCard\.phase === "intro" && currentCard\.meaning/);
  assert.match(practiceSource, /study-practice-intro-meaning/);
  assert.match(practiceSource, /audioText={currentCard\.term}/);
  assert.match(practiceSource, /study\.practice-pronunciation-guide/);
  assert.match(practiceSource, /practiceModeLabel\(mode\)/);
  assert.match(practiceSource, /Combined study/);
  assert.match(pronunciationGuideSource, /Pronunciation guide/);
  assert.match(pronunciationGuideSource, /study-pronunciation-guide-button/);
  assert.match(pronunciationGuideSource, /study-pronunciation-guide-part/);
  assert.match(pronunciationGuideSource, /study-pronunciation-guide-parts/);
  assert.match(practiceSource, /data-inventory-id="study\.practice-navigation"/);
  assert.match(practiceSource, /data-inventory-id="study\.practice-previous"/);
  assert.match(practiceSource, /data-inventory-id="study\.practice-next"/);
  assert.match(practiceSource, /currentAttempt\.answerResult === "wrong_axis"/);
  assert.match(practiceSource, /currentAttempt\.answerResult === "retry"/);
  assert.match(practiceSource, /currentAttempt\.answerResult === "idle"/);
  assert.match(practiceSource, /aria-label="Previous term"/);
  assert.match(practiceSource, /aria-label="Next term"/);
  assert.match(practiceSource, /data-inventory-id="study\.practice-not-sure"/);
  assert.match(practiceSource, /Not sure\?/);
  assert.match(practiceSource, /\/learning\/vocabulary-reviews/);
  assert.match(practiceSource, /axis_key: currentCard\.assessmentAxisKey/);
  assert.match(practiceSource, /result: answerResult,/);
  assert.match(practiceSource, /result: "incorrect"/);
  assert.doesNotMatch(practiceSource, /Type the meaning to check recall before moving on|Program mode|Review mode|Type the Russian term/);
  assert.doesNotMatch(practiceSource, /Meaning hidden until you check it|Reveal answer|Hide answer/);
  assert.match(practiceSource, /currentCard\.phase === "intro"/);
  assert.match(practiceSource, /currentCard\.phase === "assessment"/);
  assert.match(practiceSource, /Check answer/);
  assert.match(practiceSource, /Correct/);
  assert.match(practiceSource, /Try again/);
  assert.match(practiceSource, /Incorrect/);
  assert.match(practiceSource, /No practice items available/);
  assert.match(practiceSource, /Loading practice session/);
});
