const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const repoRoot = path.join(__dirname, "..", "..");
const studySource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "surface-views.tsx"), "utf8");
const dueGroupsSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "study-due-language-groups.tsx"), "utf8");
const axisChartSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "study-axis-radar-chart.tsx"), "utf8");
const mockStudySource = fs.readFileSync(path.join(repoRoot, "apps", "web", "components", "mock-route-views.tsx"), "utf8");
const stylesheetSource = fs.readFileSync(path.join(repoRoot, "apps", "web", "app", "globals.css"), "utf8");

test("Study route expands saved vocabulary rows to show full metadata", () => {
  assert.match(studySource, /study\.programs-card/);
  assert.match(studySource, /study\.program-group/);
  assert.match(studySource, /study\.program-level/);
  assert.match(studySource, /study\.program-item/);
  assert.match(studySource, /study\.program-item-toggle/);
  assert.match(studySource, /study\.program-item-details/);
  assert.match(studySource, /study\.program-item-axis-chart/);
  assert.match(studySource, /Program introduction/);
  assert.match(studySource, /Practice this level/);
  assert.match(studySource, /study\.program-practice-link-summary/);
  assert.match(studySource, /study\.queue-card/);
  assert.match(studySource, /study-queue-card-summary/);
  assert.match(studySource, /study-queue-actions/);
  assert.match(studySource, /DueReviewChart/);
  assert.match(studySource, /Due items/);
  assert.match(studySource, /Tap a language card for review pills and timing\./);
  assert.match(studySource, /Start review session/);
  assert.match(studySource, /study\.review-practice-link/);
  assert.match(dueGroupsSource, /study\.queue-language-group/);
  assert.match(dueGroupsSource, /study\.queue-language-group-toggle/);
  assert.match(dueGroupsSource, /study\.queue-language-group-details/);
  assert.match(dueGroupsSource, /study\.queue-language-term-pill/);
  assert.match(dueGroupsSource, /study\.queue-language-term-origin-legend/);
  assert.match(dueGroupsSource, /Glossed/);
  assert.match(dueGroupsSource, /Program/);
  assert.match(dueGroupsSource, /termOriginClassName/);
  assert.match(dueGroupsSource, /study\.queue-language-term-details/);
  assert.match(dueGroupsSource, /study\.queue-language-term-axis-chart/);
  assert.match(dueGroupsSource, /study\.queue-language-source-actions/);
  assert.match(dueGroupsSource, /study\.queue-language-program/);
  assert.match(dueGroupsSource, /study\.queue-language-glossed/);
  assert.match(dueGroupsSource, /study\.queue-language-both/);
  assert.match(dueGroupsSource, /language_code=/);
  assert.match(dueGroupsSource, /study\.queue-language-notify/);
  assert.match(dueGroupsSource, /study-source-toast/);
  assert.match(mockStudySource, /study\.programs-card/);
  assert.match(mockStudySource, /study\.program-group/);
  assert.match(mockStudySource, /study\.program-level/);
  assert.match(mockStudySource, /study\.program-item/);
  assert.match(mockStudySource, /study\.program-item-toggle/);
  assert.match(mockStudySource, /study\.program-item-details/);
  assert.match(mockStudySource, /study\.program-item-axis-chart/);
  assert.match(mockStudySource, /Program introduction/);
  assert.match(mockStudySource, /Practice this level/);
  assert.doesNotMatch(studySource, /study\.program-group" data-inventory-id="study\.program-group" open/);
  assert.doesNotMatch(mockStudySource, /study\.program-group" data-inventory-id="study\.program-group" open/);
  assert.match(mockStudySource, /study\.queue-card/);
  assert.match(mockStudySource, /study-queue-card-summary/);
  assert.match(mockStudySource, /study-queue-actions/);
  assert.match(mockStudySource, /DueReviewChart/);
  assert.match(mockStudySource, /Due items/);
  assert.match(mockStudySource, /Tap a language card for review pills and timing\./);
  assert.match(studySource, /study\.glossed-vocabulary-card/);
  assert.match(studySource, /study-language-group-summary/);
  assert.match(studySource, /<details key=\{group\.language_code\} className="study-language-group" data-inventory-id="study\.glossed-vocabulary-language-group">/);
  assert.doesNotMatch(studySource, /study-language-group" data-inventory-id="study\.glossed-vocabulary-language-group" open/);
  assert.match(studySource, /study\.glossed-vocabulary-item-toggle/);
  assert.match(studySource, /study-saved-item-row/);
  assert.match(studySource, /study-saved-item-term/);
  assert.match(studySource, /study-saved-item-pronunciation/);
  assert.match(studySource, /study-saved-item-meaning/);
  assert.match(studySource, /English meaning/);
  assert.match(studySource, /\(\{pronunciation\}\)/);
  assert.match(studySource, /study\.glossed-vocabulary-item-details/);
  assert.match(studySource, /study-metadata-grid/);
  assert.match(studySource, /Current note/);
  assert.match(studySource, /Source sentence/);
  assert.match(mockStudySource, /study-language-group-summary/);
  assert.match(mockStudySource, /<details key=\{group\.language_code\} className="study-language-group" data-inventory-id="study\.glossed-vocabulary-language-group">/);
  assert.doesNotMatch(mockStudySource, /study-language-group" data-inventory-id="study\.glossed-vocabulary-language-group" open/);
  assert.match(mockStudySource, /study\.glossed-vocabulary-item-toggle/);
  assert.match(mockStudySource, /study-saved-item-row/);
  assert.match(mockStudySource, /English meaning/);
  assert.match(mockStudySource, /\(\{pronunciation\}\)/);
  assert.match(mockStudySource, /study\.glossed-vocabulary-item-details/);
  assert.match(axisChartSource, /study\.glossed-vocabulary-item-axis-chart/);
  assert.doesNotMatch(studySource, /StudyPronunciationGuide|study\.practice-pronunciation-guide|study-pronunciation-guide/);
  assert.doesNotMatch(mockStudySource, /StudyPronunciationGuide|study\.practice-pronunciation-guide|study-pronunciation-guide/);
  assert.match(stylesheetSource, /\.study-pronunciation-guide\s*\{/);
  assert.match(stylesheetSource, /\.study-language-source-actions\s*\{/);
  assert.match(stylesheetSource, /\.study-language-source-action-count\s*\{/);
  assert.match(stylesheetSource, /\.study-language-term-pill--glossed\s*\{/);
  assert.match(stylesheetSource, /\.study-language-term-pill--program\s*\{/);
  assert.match(stylesheetSource, /\.study-source-toast\s*\{/);
  assert.match(stylesheetSource, /study-language-group\[open\] \.study-language-group-summary::after[\s\S]*content: "-";/);
  assert.match(stylesheetSource, /study-program-group\[open\] \.study-program-group-summary::after[\s\S]*content: "-";/);
});
